package utils

import (
	"fmt"
	"os"
	"time"

	"github.com/vic-sdd/vic/internal/config"
	"gopkg.in/yaml.v3"
)

// TechStack represents the technology stack
type TechStack struct {
	Frontend       []string `yaml:"frontend"`
	Backend        []string `yaml:"backend"`
	Database       []string `yaml:"database"`
	Infrastructure []string `yaml:"infrastructure"`
}

// ProjectYAML represents the project.yaml structure
type ProjectYAML struct {
	Name           string    `yaml:"name"`
	Version        string    `yaml:"version"`
	Status         string    `yaml:"status"`
	Description    string    `yaml:"description"`
	CreatedAt      string    `yaml:"created_at"`
	LastUpdated    string    `yaml:"last_updated"`
	TechStack      TechStack `yaml:"tech_stack"`
	Language       string    `yaml:"language"`
	PackageManager string    `yaml:"package_manager"`
	Meta           MetaYAML  `yaml:"_meta"`
}

// MetaYAML represents metadata
type MetaYAML struct {
	GeneratedBy  string         `yaml:"generated_by"`
	GeneratedAt  string         `yaml:"generated_at"`
	Confidence   ConfidenceYAML `yaml:"confidence"`
	Warnings     []string       `yaml:"warnings"`
	ManualFields []string       `yaml:"manual_fields"`
}

// ConfidenceYAML represents confidence info
type ConfidenceYAML struct {
	Score   float64  `yaml:"score"`
	Level   string   `yaml:"level"`
	Factors []string `yaml:"factors"`
}

// GenerateProjectYAML generates project.yaml
func GenerateProjectYAML(cfg *config.Config, name, tech string) {
	now := time.Now().Format("2006-01-02")

	// Parse tech stack
	var ts TechStack
	if tech != "" {
		// Simple parsing - split by comma
		// In production, would do proper language detection
		ts.Backend = []string{tech}
	}

	project := ProjectYAML{
		Name:           name,
		Version:        "0.1.0",
		Status:         "development",
		Description:    "Project description",
		CreatedAt:      now,
		LastUpdated:    now,
		TechStack:      ts,
		Language:       "auto-detected",
		PackageManager: "auto-detected",
		Meta: MetaYAML{
			GeneratedBy: "vic-go",
			GeneratedAt: time.Now().Format("2006-01-02T15:04:05Z"),
			Confidence: ConfidenceYAML{
				Score:   100,
				Level:   "high",
				Factors: []string{"freshly initialized"},
			},
			Warnings:     []string{},
			ManualFields: []string{"description", "key_features", "notes", "owner"},
		},
	}

	data, err := yaml.Marshal(project)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error marshaling project.yaml: %v\n", err)
		return
	}

	header := `# Project Metadata - VIBE-SDD
# ================================
# Auto-generated by vic-go
# Manual fields marked with [MANUAL]

`
	if err := os.WriteFile(cfg.ProjectFile, []byte(header+string(data)), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing project.yaml: %v\n", err)
	}
}

// DependencyGraphYAML represents dependency-graph.yaml
type DependencyGraphYAML struct {
	Version          string      `yaml:"version"`
	GeneratedAt      string      `yaml:"generated_at"`
	DetectedLanguage string      `yaml:"detected_language"`
	Modules          interface{} `yaml:"modules"`
	ExternalDeps     interface{} `yaml:"external_dependencies"`
	DatabaseDeps     interface{} `yaml:"database_dependencies"`
	Meta             MetaYAML    `yaml:"_meta"`
}

// GenerateDependencyGraph generates dependency-graph.yaml
func GenerateDependencyGraph(cfg *config.Config) {
	graph := DependencyGraphYAML{
		Version:          "1.0",
		GeneratedAt:      time.Now().Format("2006-01-02T15:04:05Z"),
		DetectedLanguage: "auto-detected",
		Modules:          map[string]interface{}{},
		ExternalDeps:     map[string]interface{}{},
		DatabaseDeps:     map[string]interface{}{},
		Meta: MetaYAML{
			GeneratedBy: "vic-go",
			GeneratedAt: time.Now().Format("2006-01-02T15:04:05Z"),
			Confidence: ConfidenceYAML{
				Score:   100,
				Level:   "high",
				Factors: []string{"freshly initialized"},
			},
			Warnings:     []string{},
			ManualFields: []string{"modules.*.description", "modules.*.exports"},
		},
	}

	data, err := yaml.Marshal(graph)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error marshaling dependency-graph.yaml: %v\n", err)
		return
	}

	header := `# Dependency Graph - VIBE-SDD
# =================================
# Auto-generated by vic-go

`
	if err := os.WriteFile(cfg.DependencyGraphFile, []byte(header+string(data)), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing dependency-graph.yaml: %v\n", err)
	}
}
