package utils

import (
	 "fmt"
    "os"
    "path/filepath"
    "time"

    "github.com/vic-sdd/vic/internal/config"
    "github.com/vic-sdd/vic/internal/types"
    "gopkg.in/yaml.v3"
)

// TechStack represents the technology stack
type TechStack struct {
	Frontend       []string `yaml:"frontend"`
    Backend        []string `yaml:"backend"`
    Database       []string `yaml:"database"`
    Infrastructure []string `yaml:"infrastructure"`
}

// ProjectYAML represents the project.yaml structure
type ProjectYAML struct {
	Name           string    `yaml:"name"`
	Version        string    `yaml:"version"`
	Status         string    `yaml:"status"`
	Description    string    `yaml:"description"`
	CreatedAt      string    `yaml:"created_at"`
	 LastUpdated      string    `yaml:"last_updated"`
	TechStack      TechStack `yaml:"tech_stack"`
	 Language       string    `yaml:"language"`
    PackageManager string `yaml:"package_manager"`
    Meta           MetaYAML  `yaml:"_meta"`
}

// MetaYAML represents metadata
type MetaYAML struct {
    GeneratedBy  string         `yaml:"generated_by"`
    GeneratedAt  string         `yaml:"generated_at"`
    Confidence   ConfidenceYAML `yaml:"confidence"`
    Warnings     []string       `yaml:"warnings"`
    ManualFields []string       `yaml:"manual_fields"`
}

// ConfidenceYAML represents confidence info
type ConfidenceYAML struct {
    Score   float64  `yaml:"score"`
    Level   string    `yaml:"level"`
    Factors []string    `yaml:"factors"`
}

// GenerateProjectYAML generates project.yaml
func GenerateProjectYAML(cfg *config.Config, name, tech string) {
    now := time.Now().Format("2006-01-02")

    // Parse tech stack
    var ts TechStack
    if tech != "" {
        // Simple parsing - split by comma
        // In production, would do proper language detection
        ts.Backend = []string{tech}
    }

    project := ProjectYAML{
        Name:           name,
        Version:        "0.1.0",
        Status:         "development",
        Description:    "Project description",
        CreatedAt:      now,
        LastUpdated:      now,
        TechStack:      ts,
        Language:       "auto-detected",
        PackageManager: "auto-detected",
        Meta: MetaYAML{
            GeneratedBy:  "vic-go",
            GeneratedAt: time.Now().Format("2006-01-02T15:04:05Z"),
            Confidence: ConfidenceYAML{
                Score:   100,
                Level:   "high",
                Factors: []string{"freshly initialized"},
            },
            Warnings:     []string{},
            ManualFields: []string{"description", "key_features", "notes", "owner"},
        },
    }

    data, err := yaml.Marshal(project)
    if err != nil {
        fmt.Fprintf(os.Stderr, "Error marshaling project.yaml: %v\n", err)
        return
    }

    header := `# Project Metadata - VIBE-SDD
# ================================
# Auto-generated by vic-go
# Manual fields marked with [MANUAL]

`
    if err := os.WriteFile(cfg.ProjectFile, []byte(header+string(data)), 0644); err != nil {
        fmt.Fprintf(os.Stderr, "Error writing project.yaml: %v\n", err)
    }
}

// DependencyGraphYAML represents dependency-graph.yaml
type DependencyGraphYAML struct {
    Version          string      `yaml:"version"`
    GeneratedAt      string      `yaml:"generated_at"`
    DetectedLanguage string      `yaml:"detected_language"`
    Modules          interface{} `yaml:"modules"`
    ExternalDeps     interface{} `yaml:"external_dependencies"`
    DatabaseDeps     interface{} `yaml:"database_dependencies"`
    Meta             MetaYAML  `yaml:"_meta"`
}

// GenerateDependencyGraph generates dependency-graph.yaml
func GenerateDependencyGraph(cfg *config.Config) error {
	header := `# Dependency Graph - VIBE-SDD
# ============================================
# Auto-generated by vic-go on ` + time.Now().Format("2006-01-02") + `

`
	if err := os.WriteFile(cfg.DependencyGraphFile, []byte(header), 0644); err != nil {
		return fmt.Errorf("failed to write dependency-graph.yaml: %w", err)
	}
	return nil
}

// LoadPhaseStatus loads the phase status file
func LoadPhaseStatus(cfg *config.Config) (*types.PhaseFile, error) {
    phaseFile := filepath.Join(cfg.GetVICDir(), "status", "phase.yaml")

    if !FileExists(phaseFile) {
        // Return default if doesn't exist
        return &types.PhaseFile{
            CycleID:      "default",
            CurrentPhase: 0,
            CurrentGate:  0,
            StartedAt:    time.Now().Format("2006-01-02"),
            LastUpdated:    time.Now().Format("2006-01-02"),
        }, nil
    }

    data, err := os.ReadFile(phaseFile)
    if err != nil {
        return nil, fmt.Errorf("failed to read phase file: %w", err)
    }

    var phase types.PhaseFile
    if err := yaml.Unmarshal(data, &phase); err != nil {
        return nil, fmt.Errorf("failed to parse phase file: %w", err)
    }

    return &phase, nil
}

// SavePhaseStatus saves the phase status file
func SavePhaseStatus(cfg *config.Config, phase *types.PhaseFile) error {
    phaseFile := filepath.Join(cfg.GetVICDir(), "status", "phase.yaml")

    // Ensure directory exists
    statusDir := filepath.Join(cfg.GetVICDir(), "status")
    if !FileExists(statusDir) {
        if err := os.MkdirAll(statusDir, 0755); err != nil {
            return fmt.Errorf("failed to create status directory: %w", err)
        }
    }

    data, err := yaml.Marshal(phase)
    if err != nil {
        return fmt.Errorf("failed to marshal phase: %w", err)
    }

    header := []byte(`# Phase Status - SDD Flow
# Auto-generated by vic-go
# Do not edit manually - use vic phase commands

`)
    if err := os.WriteFile(phaseFile, append(header, data...), 0644); err != nil {
        return fmt.Errorf("failed to write phase file: %w", err)
    }

    return nil
}

// LoadGateStatus loads the gate status file
func LoadGateStatus(cfg *config.Config) (map[string]types.Gate, error) {
    gateFile := filepath.Join(cfg.GetVICDir(), "status", "gate-status.yaml")

    if !FileExists(gateFile) {
        // Return default gates
        return map[string]types.Gate{
            "gate_0": {Name: "需求完整性", Phase: 0, Status: "pending"},
            "gate_1": {Name: "需求可测试", Phase: 0, Status: "pending"},
            "gate_2": {Name: "架构完整性", Phase: 1, Status: "pending"},
            "gate_3": {Name: "技术选型合理", Phase: 1, Status: "pending"},
            "gate_4": {Name: "代码可编译", Phase: 2, Status: "pending"},
            "gate_5": {Name: "代码对齐SPEC", Phase: 2, Status: "pending"},
            "gate_6": {Name: "功能测试通过", Phase: 3, Status: "pending"},
            "gate_7": {Name: "发布就绪", Phase: 3, Status: "pending"},
        }, nil
    }

    data, err := os.ReadFile(gateFile)
    if err != nil {
        return nil, fmt.Errorf("failed to read gate file: %w", err)
    }

    var gateData struct {
        Gates map[string]types.Gate `yaml:"gates"`
    }
    if err := yaml.Unmarshal(data, &gateData); err != nil {
        return nil, fmt.Errorf("failed to parse gate file: %w", err)
    }

    return gateData.Gates, nil
}

// SaveGateStatus saves the gate status file
func SaveGateStatus(cfg *config.Config, gates map[string]types.Gate) error {
    gateFile := filepath.Join(cfg.GetVICDir(), "status", "gate-status.yaml")

    // Ensure directory exists
    statusDir := filepath.Join(cfg.GetVICDir(), "status")
    if !FileExists(statusDir) {
        if err := os.MkdirAll(statusDir, 0755); err != nil {
            return fmt.Errorf("failed to create status directory: %w", err)
        }
    }

    data := map[string]interface{}{
        "gates": gates,
    }

    yamlData, err := yaml.Marshal(data)
    if err != nil {
        return fmt.Errorf("failed to marshal gates: %w", err)
    }

    header := []byte(`# Gate Status - SDD Flow
# Auto-generated by vic-go
# Do not edit manually - use vic gate commands

`)
    if err := os.WriteFile(gateFile, append(header, yamlData...), 0644); err != nil {
        return fmt.Errorf("failed to write gate file: %w", err)
    }

    return nil
}
