package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/vic-sdd/vic/internal/config"
	"github.com/vic-sdd/vic/internal/types"
	"github.com/vic-sdd/vic/internal/utils"
	"gopkg.in/yaml.v3"
)

// productMode represents a product redesign mode
type productMode struct {
	ID          string
	Name        string
	Description string
	Icon        string
	Usage       string
}

// productModes defines the four redesign modes
var productModes = []productMode{
	{
		ID:          "expansion",
		Name:        "EXPANSION - Scope Expansion",
		Description: "Dream big. Propose the ambitious version.",
		Icon:        "🚀",
		Usage:       "Explore possibilities",
	},
	{
		ID:          "selective",
		Name:        "SELECTIVE - Selective Expansion",
		Description: "Present opportunities neutrally. Let user choose.",
		Icon:        "⚖️",
		Usage:       "Evaluate trade-offs",
	},
	{
		ID:          "hold",
		Name:        "HOLD - Hold Scope",
		Description: "Maximum rigor. No expansions. Stay focused.",
		Icon:        "🔒",
		Usage:       "Ship focused",
	},
	{
		ID:          "cut",
		Name:        "CUT - Scope Reduction",
		Description: "Radical simplification. Remove what doesn't serve the core.",
		Icon:        "✂️",
		Usage:       "Ship fast",
	},
}

const productTemplate = `# Product Redesign Records - VIBE-SDD
# Auto-generated by vic-go
# Do not edit manually - use vic product commands

%s`

// NewProductCmd creates the product command
func NewProductCmd(cfg *config.Config) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "product",
		Short: "Product redesign management",
		Long:  `Manage product redesign decisions and modes.`,
	}

	cmd.AddCommand(NewProductModesCmd(cfg))
	cmd.AddCommand(NewProductRecordCmd(cfg))
	cmd.AddCommand(NewProductRecordsCmd(cfg))

	return cmd
}

// NewProductModesCmd creates the product modes subcommand
func NewProductModesCmd(cfg *config.Config) *cobra.Command {
	return &cobra.Command{
		Use:     "modes",
		Short:   "Display the four product redesign modes with examples.",
		Example: `  vic product modes`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runProductModes()
		},
	}
}

func runProductModes() error {
	var builder strings.Builder

	// Header
	builder.WriteString("═══════════════════════════════════════════════════════════\n")
	builder.WriteString("  🚀 Product Redesign - The Four Modes\n")
	builder.WriteString("═══════════════════════════════════════════════════════════\n\n")

	// Expansion Mode
	builder.WriteString("┌─────────────────────────────────────────────────────────┐\n")
	builder.WriteString("│ 1. EXPANSION - Scope Expansion                          │\n")
	builder.WriteString("├─────────────────────────────────────────────────────────┤\n")
	builder.WriteString("│ Dream big. Propose the ambitious version.                │\n")
	builder.WriteString("│                                                         │\n")
	builder.WriteString("│ Example:                                                │\n")
	builder.WriteString("│ \"User wants photo upload\"                               │\n")
	builder.WriteString("│ → \"What if we auto-detect product from photo?\"          │\n")
	builder.WriteString("│ → \"What if we draft descriptions automatically?\"         │\n")
	builder.WriteString("│ → \"What if we suggest the best hero image?\"            │\n")
	builder.WriteString("│                                                         │\n")
	builder.WriteString("│ Icon: 🚀 | When: Explore possibilities                    │\n")
	builder.WriteString("└─────────────────────────────────────────────────────────┘\n\n")

	// Selective Mode
	builder.WriteString("┌─────────────────────────────────────────────────────────┐\n")
	builder.WriteString("│ 2. SELECTIVE - Selective Expansion                     │\n")
	builder.WriteString("├─────────────────────────────────────────────────────────┤\n")
	builder.WriteString("│ Present opportunities neutrally. Let user choose.       │\n")
	builder.WriteString("│                                                         │\n")
	builder.WriteString("│ Example:                                                │\n")
	builder.WriteString("│ ┌────────────────────────────────────┐                 │\n")
	builder.WriteString("│ │ Opportunity A                      │                 │\n")
	builder.WriteString("│ │ Effort: Medium | Impact: High      │                 │\n")
	builder.WriteString("│ │ Why: Saves users 10 mins           │                 │\n")
	builder.WriteString("│ └────────────────────────────────────┘                 │\n")
	builder.WriteString("│                                                         │\n")
	builder.WriteString("│ Icon: ⚖️ | When: Evaluate trade-offs                    │\n")
	builder.WriteString("└─────────────────────────────────────────────────────────┘\n\n")

	// Hold Mode
	builder.WriteString("┌─────────────────────────────────────────────────────────┐\n")
	builder.WriteString("│ 3. HOLD - Hold Scope                                   │\n")
	builder.WriteString("├─────────────────────────────────────────────────────────┤\n")
	builder.WriteString("│ Maximum rigor. No expansions. Stay focused.              │\n")
	builder.WriteString("│                                                         │\n")
	builder.WriteString("│ \"Let's lock down the current scope and ship.\"           │\n")
	builder.WriteString("│                                                         │\n")
	builder.WriteString("│ Icon: 🔒 | When: Ship focused                           │\n")
	builder.WriteString("└─────────────────────────────────────────────────────────┘\n\n")

	// Cut Mode
	builder.WriteString("┌─────────────────────────────────────────────────────────┐\n")
	builder.WriteString("│ 4. CUT - Scope Reduction                               │\n")
	builder.WriteString("├─────────────────────────────────────────────────────────┤\n")
	builder.WriteString("│ Radical simplification. Remove what doesn't serve the core.│\n")
	builder.WriteString("│                                                         │\n")
	builder.WriteString("│ \"Remove unused features. Focus on the 80/20.\"          │\n")
	builder.WriteString("│                                                         │\n")
	builder.WriteString("│ Icon: ✂️ | When: Ship fast                             │\n")
	builder.WriteString("└─────────────────────────────────────────────────────────┘\n\n")

	// Usage
	builder.WriteString("═══════════════════════════════════════════════════════════\n")
	builder.WriteString("  Usage: vic product record --original \"...\" --real \"...\" --mode [mode]\n")
	builder.WriteString("═══════════════════════════════════════════════════════════\n")

	fmt.Println(builder.String())

	return nil
}

// NewProductRecordCmd creates the product record subcommand
func NewProductRecordCmd(cfg *config.Config) *cobra.Command {
	var original, real, mode string

	cmd := &cobra.Command{
		Use:   "record",
		Short: "Record a product redesign decision",
		Long:  `Record a product redesign decision with original vs real implementation.`,
		Example: `  vic product record --original "User wants photo upload" --real "Auto-detect product from photo" --mode expansion
  vic product record --original "Complex checkout flow" --real "Simple 1-step checkout" --mode cut`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runProductRecord(cfg, original, real, mode)
		},
	}

	cmd.Flags().StringVarP(&original, "original", "o", "", "Original user request or problem")
	cmd.Flags().StringVarP(&real, "real", "r", "", "Real implementation or solution")
	cmd.Flags().StringVarP(&mode, "mode", "m", "", "Product mode (expansion, selective, hold, cut)")

	cmd.MarkFlagRequired("original")
	cmd.MarkFlagRequired("real")
	cmd.MarkFlagRequired("mode")

	return cmd
}

func runProductRecord(cfg *config.Config, original, real, mode string) error {
	// Validate mode
	validModes := map[string]bool{
		"expansion": true,
		"selective": true,
		"hold":      true,
		"cut":       true,
	}

	if !validModes[mode] {
		return fmt.Errorf("invalid mode: %s. Must be one of: expansion, selective, hold, cut", mode)
	}

	// Load existing records
	records, err := loadProductRecords(cfg)
	if err != nil {
		return fmt.Errorf("failed to load product records: %w", err)
	}

	// Add new record
	record := types.ProductRecord{
		ID:        fmt.Sprintf("PR-%s", time.Now().Format("20060102-150405")),
		Original:  original,
		Real:      real,
		Mode:      mode,
		Timestamp: time.Now().Format("2006-01-02 15:04:05"),
	}

	records = append(records, record)

	// Save records
	if err := saveProductRecords(cfg, records); err != nil {
		return fmt.Errorf("failed to save product records: %w", err)
	}

	// Output result
	fmt.Printf("✅ Product redesign recorded: %s\n", record.ID)
	fmt.Printf("   Original: %s\n", original)
	fmt.Printf("   Real: %s\n", real)
	fmt.Printf("   Mode: %s\n", strings.ToUpper(mode))

	return nil
}

// NewProductRecordsCmd creates the product records subcommand
func NewProductRecordsCmd(cfg *config.Config) *cobra.Command {
	var format string

	cmd := &cobra.Command{
		Use:     "records",
		Short:   "List all product redesign records",
		Long:    `List all product redesign records.`,
		Example: `  vic product records
  vic product records --format json`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runProductRecords(cfg, format)
		},
	}

	cmd.Flags().StringVarP(&format, "format", "f", "plain", "Output format (plain, json)")

	return cmd
}

func runProductRecords(cfg *config.Config, format string) error {
	records, err := loadProductRecords(cfg)
	if err != nil {
		return fmt.Errorf("failed to load product records: %w", err)
	}

	if format == "json" {
		data, err := yaml.Marshal(records)
		if err != nil {
			return fmt.Errorf("failed to marshal product records: %w", err)
		}

		header := []byte(`# Product Redesign Records - VIBE-SDD
# Auto-generated by vic-go
# Do not edit manually - use vic product commands

`)
		fmt.Printf("%s%s", header, data)
		return nil
	}

	if len(records) == 0 {
		fmt.Println("No product redesign records found.")
		fmt.Println("Use 'vic product record' to add your first record.")
		return nil
	}

	fmt.Println("📋 Product Redesign Records")
	fmt.Println("==========================")

	for i, record := range records {
		fmt.Printf("\n%d. %s\n", i+1, record.ID)
		fmt.Printf("   Time: %s\n", record.Timestamp)
		fmt.Printf("   Mode: %s\n", strings.ToUpper(record.Mode))
		fmt.Printf("   Original: %s\n", record.Original)
		fmt.Printf("   Real: %s\n", record.Real)
	}

	return nil
}

// loadProductRecords loads product records from file
func loadProductRecords(cfg *config.Config) ([]types.ProductRecord, error) {
	path := filepath.Join(cfg.ProjectDir, ".vic-sdd", "product-records.yaml")

	if !utils.FileExists(path) {
		return []types.ProductRecord{}, nil
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var records []types.ProductRecord
	if err := yaml.Unmarshal(data, &records); err != nil {
		return nil, err
	}

	return records, nil
}

// saveProductRecords saves product records to file
func saveProductRecords(cfg *config.Config, records []types.ProductRecord) error {
	// Ensure directory exists
	dir := filepath.Join(cfg.ProjectDir, ".vic-sdd")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// Marshal to YAML
	data, err := yaml.Marshal(records)
	if err != nil {
		return err
	}

	// Write to file
	path := filepath.Join(cfg.ProjectDir, ".vic-sdd", "product-records.yaml")
	return os.WriteFile(path, data, 0644)
}